# -*- coding: utf-8 -*-
"""day01_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15f74Evhh9HsYXQVMkpVBEJGmU2dRBS_F
"""

# Day 01 of my 30 days of python challenge
# Practicing basic printing
print('Faiza')
print(26)
print(176)
print('Faiza', 26)
print('Faiza', 26, 176)
print('Faiza', ',', 26, ',', 176) # output has spaces
# use string formatting to get rid of spaces:
print(f"{'Faiza'}, {26}, {176}") # space after commmas
print(f"{'Faiza'},{26},{176}") # no space after commas
print() # line gap
print('\n') # also line gap
# Variables
name = 'Faiza'
age = 26
height = 176
print(name)
print(age)
print(height)
print(name, age)
print(name, age, height)
print(f"{name} is {age} years old, and {height} cm.")
print(f"{name} is {height} cm tall.")
print(f"{age} year old {name} is {height} cm tall.")
print()

# Basic maths
print(2+3)
print(7-2)
print(2 * 2)
print(2 ** 2) # 2 to the power of 2
print(10-5)
print(15-10)
print(10/2) # note: when using divide, ouput is given to 1 dp
print(15/3)
print(10+6/2-3) # follows bidmas as default
print(((10+6)/2)-3) # use brackets to change the order to how you want
print((10+6)/(2-3))
print(10+6/(2-3))
print()
# area of triangle = 0.5 * base * height
print(0.5 * 4 * 8) # output is 1dp as we used 1dp in calc
base = 4
height = 8
print(0.5*base*height) # same result using variable
# its best practice to leave gaps so this is better:
print(0.5 * base * height)
area = 0.5 * base * height
print(area)
print("The area of the triangle is:", area)