# -*- coding: utf-8 -*-
"""day03_conditionals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_LsrhiAGV-4KVgc36PeqSB5dSPhkVFR
"""

# user inputs
name = input("What's your name? ")
print(f"Hello {name.strip().title()}, it's nice to meet you!") # when i run the cell, it asks what my name is and the output is created
# note: print prints exactly how the user entered their name eg no caps, title, all upper, spaces etc - so can we format using .title() and .strip()
hobby = input("What's your favourite hobby? ")
print(f"{name.strip().title()}, it's interesting that you enjoy {hobby.strip()}.")
print()

number = int(input("Enter a number of your choice. ")) # we have to use int() to convert input into a number as input() always gives a string
if number > 0: # theres no 'then' for condiitons in python, we use : instead and indent the next line
    status = "Positive"
elif number < 0: # elif = else if, used for mutually exclusive conditions
    status = "Negative"
else:
    status = "Zero"
print(f"{number} is {status}.")
print()

colour = input("What's your favourite colour? ")
if colour == "green":
  print("Nice choice!")
else:
  print("Cool :).")
print()

age = int(input("How old are you? "))
if age < 13:
  group = "Minor"
elif age >= 13 and age < 20:
  group = "Teen"
else:
  group = "Adult"
print(f"{name.strip().title()}, you are a {group}.")
print()

prompt = input("Enter password to continue. ")
if prompt == "python123":
  print("Access granted.")
else:
  print("Access denied.")
print()

numb = int(input("What's your favourite number? "))
if numb % 2 == 0: # % = divide, so if a number can be divided by 2, its even, otherwise its odd
  print("Your favourite number is even!")
else:
  print("Your favourite number is odd!")